# Generated by Django 4.2.7 on 2025-06-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0002_author_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('authors', models.ManyToManyField(to='reldemo.author')),
            ],
        ),
    ]
