# Generated by Django 4.2.7 on 2025-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldemo', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='reldemo.course')),
            ],
        ),
    ]
